version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  with-chrome:
    docker:
      - image: "cypress/browsers:node14.16.0-chrome90-ff88"
workflows:
  # nightly run configration
  nightly:
    triggers:
      - schedule:
          cron: "30 17 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - cypress/run:
          executor: with-chrome
          browser: chrome
          spec: cypress/integration/launch.feature
          filters:
            branches:
              only:
                - master

  # git push run configration
  build:
    jobs:
      - cypress/run:
          executor: with-chrome
          browser: chrome
          spec: cypress/integration/testing.feature
          filters:
            branches:
              only:
                - master
          post-steps:
            - store_artifacts:
                path: cypress/report
            - store_test_results:
                path: cypress/results
